-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 23:11:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `School` VARCHAR(45) NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  `Standing` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `School` VARCHAR(45) NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  `Standing` VARCHAR(45) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recruiter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recruiter` (
  `RecruiterID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Fname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `CompanyName` VARCHAR(75) NOT NULL,
  `Lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RecruiterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `ProjectID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(75) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `StudentID` INT NOT NULL,
  PRIMARY KEY (`ProjectID`),
  INDEX `fk_Projects_Student1_idx` (`StudentID` ASC),
  CONSTRAINT `Student_ID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keyword` (
  `KeywordID` INT NOT NULL AUTO_INCREMENT,
  `Keyword` VARCHAR(45) NOT NULL,
  `fk_Keyword_ProjectID` INT NOT NULL,
  PRIMARY KEY (`KeywordID`, `fk_Keyword_ProjectID`),
  INDEX `ProjectID_idx` (`fk_Keyword_ProjectID` ASC),
  CONSTRAINT `fk_Keyword_ProjectID`
    FOREIGN KEY (`fk_Keyword_ProjectID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Image` (
  `ImageID` INT NOT NULL AUTO_INCREMENT,
  `ImageURL` VARCHAR(1000) NOT NULL,
  `fk_Image_Project_ID` INT NOT NULL,
  PRIMARY KEY (`ImageID`, `fk_Image_Project_ID`),
  INDEX `ProjectID_idx` (`fk_Image_Project_ID` ASC),
  CONSTRAINT `fk_Image_ProjectID`
    FOREIGN KEY (`fk_Image_Project_ID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`File`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`File` (
  `FileID` INT NOT NULL AUTO_INCREMENT,
  `FileURL` VARCHAR(1000) NOT NULL,
  `fk_Keyword_ProjectID` INT NOT NULL,
  PRIMARY KEY (`FileID`, `fk_Keyword_ProjectID`),
  INDEX `ProjectID_idx` (`fk_Keyword_ProjectID` ASC),
  CONSTRAINT `fk_File_ProjectID`
    FOREIGN KEY (`fk_Keyword_ProjectID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjectRecruiterInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProjectRecruiterInfo` (
  `fk_Info_Project_ID` INT NOT NULL,
  `fk_Info_Recruiter_ID` INT NULL,
  INDEX `RecruiterID_idx` (`fk_Info_Recruiter_ID` ASC),
  INDEX `ProjectID_idx` (`fk_Info_Project_ID` ASC),
  CONSTRAINT `fk_Info_ProjectID`
    FOREIGN KEY (`fk_Info_Project_ID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Info_RecruiterID`
    FOREIGN KEY (`fk_Info_Recruiter_ID`)
    REFERENCES `mydb`.`Recruiter` (`RecruiterID`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
